### PR TITLE
added auth and home screen

### PR DESCRIPTION
**Pull request by sahil-patel6**
Added sign in and sign up. home screen is ready with pulling data from firestore and inserting in to the required fields

### CODE REVIEW

**Comment by Harshithpabbati** [comment]
Great work

**Comment by HarshKhandeparkar** [comment]
Done. :heavy_check_mark:

**Comment by sahil-patel6** [comment]
Thanks

**Comment by HarshKhandeparkar** [comment]
:tada: :tada: :tada:

**Comment by sahil-patel6** [comment]
Thanks

**Comment by sahil-patel6** [comment]
Thanks

**Pull request merged**
